services:
  hsccloud:
    build:
      context: ./hsccloud
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080

  nginx_server:
    build:
      context: ./nginx_server
      dockerfile: Dockerfile
    ports:
      - "80:80"
